defmodule LynxplanningpokerWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :lynxplanningpoker

  # Session cookie is signed AND encrypted. The only payload today is the
  # current_user_id UUID (not secret), so signing alone would suffice; the
  # encryption_salt is defense-in-depth so future additions to the session
  # don't accidentally leak. same_site: "Strict" is safe here because the app
  # has no cross-site flows — every entry point is same-origin navigation.
  @session_options [
    store: :cookie,
    key: "_lynxplanningpoker_key",
    signing_salt: "CfstbrZC",
    encryption_salt: "TwURRK5y",
    same_site: "Strict"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :lynxplanningpoker,
    gzip: not code_reloading?,
    only: LynxplanningpokerWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :lynxplanningpoker
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug LynxplanningpokerWeb.Router
end
