defmodule LynxplanningpokerWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :lynxplanningpoker

  # Session cookie is signed AND encrypted. The only payload today is the
  # current_user_id UUID (not secret), so signing alone would suffice; the
  # encryption_salt is defense-in-depth so future additions to the session
  # don't accidentally leak. same_site: "Strict" is safe here because the app
  # has no cross-site flows — every entry point is same-origin navigation.
  @session_options [
    store: :cookie,
    key: "_lynxplanningpoker_key",
    signing_salt: "CfstbrZC",
    encryption_salt: "TwURRK5y",
    same_site: "Strict"
  ]

  # `timeout` (default 60s) is how long the transport waits for *any* frame from
  # the client before closing the socket. In a quiet room the only thing the
  # client sends is the LiveView heartbeat, every 30s — and browsers throttle
  # timers in a hidden tab: Chrome drops background wake-ups to roughly once a
  # minute, and once the tab has been hidden for a few minutes ("intensive
  # throttling", the same resource-saving behaviour as Memory Saver) to about
  # once every five. With the default timeout the server closes a perfectly
  # healthy connection while the person is merely on another tab; Presence then
  # reports a leave and `RoomLive.Show` cleans the participant out of the room.
  #
  # 6 minutes clears even the slowest throttled heartbeat, and it does not delay
  # real departures: closing the tab or navigating away sends a WebSocket close
  # frame, which is handled at once. The timeout only covers connections that go
  # silent without closing (network drop, laptop suspend).
  @socket_timeout_ms 360_000

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options], timeout: @socket_timeout_ms],
    longpoll: [connect_info: [session: @session_options]]

  # Bounce every non-canonical host (e.g. the Fly *.fly.dev subdomain) to the
  # canonical public host before anything else runs. No-op outside :prod.
  plug LynxplanningpokerWeb.Plugs.CanonicalHost

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :lynxplanningpoker,
    gzip: not code_reloading?,
    only: LynxplanningpokerWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :lynxplanningpoker
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug LynxplanningpokerWeb.Router
end
